### ISSUE TITLE
Wrong score in isMoveDoable in custom move.

### ISSUE THREAD

**Issue by AlexeyTrefilov** [TimefoldAI/timefold-solver#589] opened 2024-01-24 14:52 UTC
**Describe the bug**
If I try to access the score from isMoveDoable in custom move, I'll get a wrong value. I've created a fork for nQueens to demonstrate that. 
The code:
```
    @Override
    public boolean isMoveDoable(ScoreDirector<NQueens> scoreDirector) {
        System.out.println(this+": "+scoreDirector.getWorkingSolution().getScore());
        //System.out.println(toDisplayString(scoreDirector.getWorkingSolution()));
        return queen.getRow()!= row;
    }
```
gives something like:
```
Queen-0: Row-6 -> Row-0: 0
Queen-0: Row-6 -> Row-0: 0
Queen-0: Row-6 -> Row-1: -2
Queen-0: Row-6 -> Row-1: -2
Queen-0: Row-6 -> Row-2: -2
Queen-0: Row-6 -> Row-2: -2
Queen-0: Row-6 -> Row-3: -2
Queen-0: Row-6 -> Row-3: -2
Queen-0: Row-6 -> Row-4: -2
Queen-0: Row-6 -> Row-4: -2
Queen-0: Row-6 -> Row-5: -2
Queen-0: Row-6 -> Row-5: -2
Queen-0: Row-6 -> Row-6: -2
Queen-0: Row-6 -> Row-7: -2
Queen-0: Row-6 -> Row-7: -2
Queen-1: Row-1 -> Row-0: -2
Queen-1: Row-1 -> Row-0: -2
Queen-1: Row-1 -> Row-1: -2
...
```
**Expected behavior**
I've expected the same value until accepted move.

**Actual behavior**
The values are different.

**To Reproduce**
See brunch isMoveDoableScore. Run NQueensHelloWorld.
https://github.com/AlexeyTrefilov/timefold-solver/tree/isMoveDoableScore

## Environment

**Timefold Solver Version or Git ref**: 

1.6.0

**Output of `java -version`:**
java version "21" 2023-09-19 LTS
Java(TM) SE Runtime Environment (build 21+35-LTS-2513)
Java HotSpot(TM) 64-Bit Server VM (build 21+35-LTS-2513, mixed mode, sharing)

**Output of `uname -a` or `ver`:**
Microsoft Windows [Version 10.0.22621.3007]

**Comment by triceo** [comment] 2024-01-24 15:28
Hello @AlexeyTrefilov, and thanks for reporting!

This is in all likelihood not a bug. We do not give any guarantees about the score during move processing. What you're seeing is most likely the score from the previous move, before it was undone.

After a move is undone and before the next move is attempted, we do not recalculate the score. It would be a pointless waste of time - the score would have been immediately overwritten by the score computed when the next move is attempted.

If you want to make sure your custom moves operate correctly, use one of the environment modes, such as `FULL_ASSERT`. Finally, be aware that custom moves are not part of the public API, and therefore anything in that area can change at any time, without prior warning.

I am going to close this issue now. Please reopen if you see the solver producing wrong scores on best solutions.

**Closed by triceo** 2024-01-24 15:28 UTC
Labels: bug, process/needs triage

**Comment by AlexeyTrefilov** [comment] 2024-01-24 16:32
Thank you for answer.
Is it possible to access current score somehow else?
I think it must be stored somewhere, because it is no point to recalculate score with undoMove.
Or may be it is possible to get score of the best solution?

**Comment by triceo** [comment] 2024-01-24 16:54
You may be able to take the working solution and use `SolutionManager` to analyze it. That said, this will be slow, and may even require you to clone the solution, making it even slower. Practically speaking, I think it is currently not possible to operate on the score inside moves.
