### ISSUE TITLE
Bug: Errors when I try to use both  @PlanningListVariable and @PlanningVariable in one project

### ISSUE THREAD

**Issue by seallijian** [TimefoldAI/timefold-solver#1120] opened 2024-10-01 02:14 UTC
**Describe the bug**

When I try to use both @PlanningListVariable and @PlanningVariable in one project,  I got error below.
Caused by: java.lang.IllegalArgumentException: The config (ValueSelectorConfig(null)) has no configured variableName for entityClass (class com.tmtblback.dto.LessonDto) and because there are multiple variableNames ([room, studentGroups, timeslot]), it cannot be deduced automatically.

**Comment by Christopher-Chianelli** [comment] 2024-10-01 04:30
Duplicate of https://github.com/TimefoldAI/timefold-solver/issues/683 ; Currently, using `PlanningListVariable` with `PlanningVariable` is not supported.

**Comment by triceo** [comment] 2024-10-01 05:56
As this is a duplicate, I will close this one.
Thank you for reporting anyway, @seallijian!

**Closed by triceo** 2024-10-01 05:56 UTC
Labels: bug
