### ISSUE TITLE
Feat: WarmStartSolveMerge - the easy problemfactchange

### ISSUE THREAD

**Issue by ge0ffrey** [TimefoldAI/timefold-solver#227] opened 2023-08-21 10:04 UTC
Motivation:

- When one or more of the problem fact changes, we want to warm restart the solver
-- called from a different thread
-- recycled the assignments as much as possible (hence "warm")
- ProblemFactChange is too much work, as it needs a different one for each possible change.

Strawman:

```
solver.solve(nurseRoster)
...
// After a bit of solving
// Mon = Ann, Tue = Beth, Wed = Carl
...
// On a different thread
remove(Beth); add(Dan); Tues.setName(Tuesday);
solver.warmStartSolveMerge(newNurseRoster).
// On main thread
// solver restarts
// uses newNurseRoster
// ports planning values from original nurseRoster
// Mon = Ann, Tuesday = Beth, Wed = null
...
// After a bit of solving
// Mon = Ann, Tuesday = Beth, Wed = Dan


```

**Comment by triceo** [comment] 2023-11-15 07:03
Closing as duplicate of https://github.com/TimefoldAI/timefold-solver/issues/149

**Closed by triceo** 2023-11-15 07:03 UTC
Labels: enhancement, process/needs triage
