### ISSUE TITLE
timefold solver migration bugs

### ISSUE THREAD

**Issue by marinier** [TimefoldAI/timefold-solver#307] opened 2023-10-06 11:33 UTC
**Describe the bug**
I used the timefold solver migration to update my optaplanner project to timefold. This broke my build and I had to manually fix it.

**Expected behavior**
I expected the process to result in code that would compile.

**Actual behavior**

This import was removed from two files that needed it:

```java
import javafx.util.StringConverter;
```

This line in `module-info.java` was not updated:

```java
requires transitive org.optaplanner.core.impl;
```

**To Reproduce**

I used this command line in powershell:

```
mvn org.openrewrite.maven:rewrite-maven-plugin:5.7.1:run "-Drewrite.recipeArtifactCoordinates=ai.timefold.solver:timefold-solver-migration:1.2.0" "-Drewrite.activeRecipes=ai.timefold.solver.migration.ToLatest"
```

## Environment

Going from OptaPlanner 9.44.0.Final to TimeFold 1.2.0

**Output of `java -version`:**

openjdk version "17.0.8.1" 2023-08-24
OpenJDK Runtime Environment Temurin-17.0.8.1+1 (build 17.0.8.1+1)
OpenJDK 64-Bit Server VM Temurin-17.0.8.1+1 (build 17.0.8.1+1, mixed mode, sharing)

**Output of `uname -a` or `ver`:**

Windows 11 Pro 10.0.22621 Build 22621

## Additional information

N/A

**Comment by triceo** [comment] 2023-10-06 17:01
Thanks for reporting, @marinier!
If you could provide code to reproduce this behavior, that would be helpful; otherwise it's hard to know what to fix, or to confirm that the fix is correct.

**Comment by marinier** [comment] 2023-10-07 18:36
Here you go. This is a really dumb example that doesn't do anything, but if you run the migration on it you'll see the issues I described above.

[example.zip](https://github.com/TimefoldAI/timefold-solver/files/12838507/example.zip)

**Comment by triceo** [comment] 2023-10-07 18:45
@marinier Thank you!

**Comment by jhult** [comment] 2023-12-27 18:18
I debugged the [above example zip](https://github.com/TimefoldAI/timefold-solver/files/12838507/example.zip) by running this command:

```
mvn org.openrewrite.maven:rewrite-maven-plugin:LATEST:run \
  -Drewrite.recipeArtifactCoordinates=ai.timefold.solver:timefold-solver-migration:LATEST \
  -Drewrite.activeRecipes=ai.timefold.solver.migration.ToLatest
```

The issues appear to be due to [OpenRewrite](https://github.com/openrewrite/rewrite) not supporting [modules](https://en.wikipedia.org/wiki/Java_Platform_Module_System):

- https://github.com/openrewrite/rewrite/issues/1895
- https://github.com/openrewrite/rewrite/pull/1925

**Comment by triceo** [comment] 2023-12-27 18:56
@jhult Thanks for the investigation! Modules would explain why we weren't able to reproduce in any of our own cases - we don't use them.

**Comment by marinier** [comment] 2024-01-02 14:43
Lack of module support would explain the issue with module-info.java, but the issue with the import being removed appears to be a separate problem.

**Comment by jhult** [comment] 2024-01-03 16:59
@marinier, based on my debugging, I believe both issues are related to module support. `org.openjfx:javafx-graphics` is listed as a dependency in `pom.xml`. However, when checking for unused imports, `javafx.util.StringConverter` is not recognized as on the classpath by OpenRewrite and thus is (incorrectly) removed.

**Comment by ge0ffrey** [comment] 2024-01-24 10:37
If its an OpenRewrite bug, can we create an issue upstream and close this one?

**Comment by jhult** [comment] 2024-01-24 14:48
@ge0ffrey, yes, I believe it is a bug in OpenRewrite and we can close this issue. I think the following (already open) bug suffices: https://github.com/openrewrite/rewrite/issues/1895

**Comment by triceo** [comment] 2024-01-24 15:29
Thank you, @jhult. I will subscribe to the issue you pointed out.

**Closed by triceo** 2024-01-24 15:29 UTC
Labels: bug, component/migration
